### PR TITLE
Allow AFIT where needed to suppress warnings

### PR DESCRIPTION
**Pull request by plaes**

### CODE REVIEW

**Comment by lucasgranberg** [comment]
Can this be done globally by placing `#![allow(async_fn_in_trait)]
`  in lib.rs of lora-phy and lorawan-device?

**Comment by plaes** [comment]
> Can this be done globally by placing `#![allow(async_fn_in_trait)] ` in lib.rs of lora-phy and lorawan-device?

It can be (and it was like that before), but I would rather be explicit and only tag traits that actually need this.

**Review by lucasgranberg — APPROVED** [review]
I think allowing in lib.rs would be better as lorawan-device and lora-phy will be used in single threaded embedded context, at least so far. If not than then actually doing the whole Feature + Send thing could work too.

Anyway I don't feel that strongly about it, lets do it your way.

**Comment by lthiery** [comment]
I don't have a preference on style here. I think this works!

**Review by lthiery — APPROVED** [review]

**Pull request merged**
