### PR TITLE
Drop GenericArray requirement from lorawan-device

### PR DESCRIPTION
**Pull request by plaes**
This is first step towards #126, though I have some doubts whether this is implemented in acceptable way...

### CODE REVIEW

**Comment by lucasgranberg** [comment]
Maybe this is a step in a grander plan but I don't see this making that big of a difference. Now lorawan-device requires DataPayloadArray which is a GenericArray anyway. Not having to have the right version of GenericArray is a plus but the same could be achieved with an re-export.

I am playing around with just ripping out generic-array from everywhere except default-crypto and using [u8;256] and [u8;16] instead. Only snaffoo is I can't seem to convert a GenericArray to an [u8].

https://github.com/lora-rs/lora-rs/compare/main...lucasgranberg:lora-rs:rip-generic-array

**Comment by plaes** [comment]
@lucasgranberg Grand plan is this - https://github.com/lora-rs/lora-rs/issues/126#issuecomment-2357778569

**Comment by lucasgranberg** [comment]
Yes but why even bother with GenericArray/HybridArray. We don't need generic lengths on our arrays as we know what they should be. Only reason GenericArray was used was for passing in to the crypto stuff. That can still be done inside default-crypto. We can just use Rust arrays and slices in the rest of the code.

**Comment by plaes** [comment]
Handled in #309

**Pull request closed without merging**
