### PR TITLE
lorawan-encoding: Add module with various packet length values

### PR DESCRIPTION
**Pull request by plaes**
Parts of commit extracted from PR #142, and eventualy dependency for #198.

### CODE REVIEW

**Comment by lthiery** [comment]
I think there are some issues with some of these values. I am expecting to see JOIN_ACCEPT_MAX equal to 33 but it comes out to only 28 here. It looks like you are neglecting to warp the JoinRequest with MHDR and MIC at the end.

Here are the references from the LoRaWAN Specification

image

The PHYPayload length is what we will want to pass into the lora_modulation calculator. Note: the CRC configuration is accounted for in `BaseBandModulationParams`, so I think your `UPLINK_CRC` and `UPLINK/DOWNLINK_OVERHEAD` should be removed.

You can see from the above figure, we have:
```
DATA_FRAME = MHDR + MACPayload + MIC;
JOIN_REQUEST = MHDR + JOIN_REQUEST_PAYLOAD + MIC;
JOIN_ACCEPT = MHDR + JOIN_ACCEPT_PAYLOAD + MIC;
```

Also, the next figure makes it easy to get `MHDR` and `MIC` but you have set those properly already:

image

So for JOIN_ACCEPT_MAX, you can look at the JOIN_REQUEST frame, which you extracted properly as well:

image

So I think we will see:
```
// JoinNonce, NetID, DevAddr, DLSettings, RxDelay
JOIN_ACCEPT_PAYLOAD_MIN = 3+3+4+1+1
// Optional CFList
JOIN_ACCEPT_PAYLOAD_MAX = JOIN_ACCEPT_PAYLOAD_MIN + 16
```

So the final values you will have are
```
JOIN_ACCEPT_MIN = MHDR + JOIN_ACCEPT_PAYLOAD_IN + MIC;
JOIN_ACCEPT_MAX = MHDR + JOIN_ACCEPT_PAYLOAD_MAX + MIC;
``

**Comment by lthiery** [comment]
Woops, I totally missed the redeclaration of the OVERHEAD variables
```
    pub const UPLINK_OVERHEAD: u8 = UPLINK_CRC;
    pub const DOWNLINK_OVERHEAD: u8 = 0;

    pub mod mac {
        pub const UPLINK_OVERHEAD: u8 = super::UPLINK_OVERHEAD + MHDR + MIC;
        pub const DOWNLINK_OVERHEAD: u8 = super::DOWNLINK_OVERHEAD + MHDR + MIC;
  ```

**Comment by plaes** [comment]
Let's put this PR on hold for now, I managed to figure out the preamble detection on sx1272, so maybe we don't even need this.

**Comment by lthiery** [comment]
heh I liked using it in more in the encoding code like I did in PR to you
https://github.com/plaes/lora-rs/pull/2

**Comment by lthiery** [comment]
Replace by #206

**Pull request closed without merging**
