### PR TITLE
lorawan-encoding: Rename NewSKey to NwkSKey

### PR DESCRIPTION
**Pull request by plaes**
Should be mostly backwards compatible.

### CODE REVIEW

**Review by lthiery — APPROVED** [review]
Fine by me pending clippy/fmt

**Comment by plaes** [comment]
First step is done, lorawan-device will be somewhat more work as `newskey` is also public member of some structs..

**Comment by plaes** [comment]
And second step is also done. But `newskey` is still used as public member of struct in at least 3 places:

https://github.com/lora-rs/lora-rs/blob/97addb9b385a01c9e64acb2d2cb1222ddf92812a/lorawan-device/src/mac/session.rs#L36-L40

https://github.com/lora-rs/lora-rs/blob/97addb9b385a01c9e64acb2d2cb1222ddf92812a/lorawan-device/src/mac/session.rs#L24-L32

https://github.com/lora-rs/lora-rs/blob/97addb9b385a01c9e64acb2d2cb1222ddf92812a/lorawan-device/src/lib.rs#L75-L79

**Comment by lthiery** [comment]
I doubt many folks are using these newskey interfaces. I'd be OK with a breaking change and a version bump next time we do a release.

**Review by lthiery — APPROVED** [review]

**Pull request merged**
